### ISSUE TITLE
Feedback Form Overflows Screen Bounds on Mobile

### ISSUE THREAD

**Issue by KaylaLincoln** [DerekFoulk/nwca-nitrosell#79]
Accidently clicked the "Feedback" button and the forum was too large to close (overflowed the screen). Had to refresh page in order to close.

Browser: Google Chrome
Device: Note 4

**Comment by DerekFoulk** [comment]
Feedback button should be hidden on mobile devices.

**Comment by DerekFoulk** [comment]
This issue was fixed with the release of 86dd8e4.
