### ISSUE TITLE
Category image missing on department page

### ISSUE THREAD

**Issue by KaylaLincoln** [DerekFoulk/nwca-nitrosell#80]
http://nwca.com/Networking-Cables/148/

![screenshot_2015-07-29-21-51-16](https://cloud.githubusercontent.com/assets/11843096/8976054/57bc71f8-363c-11e5-9030-0ed54715a6f8.png)

**Comment by DerekFoulk** [comment]
Category images are not receiving XML Mapped Images.

**Comment by DerekFoulk** [comment]
This issue was resolved with the release of 587656e.
